=== psiegel/eventdeck/debug/whq-tables-schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Warhammer Quest Monster and Event table schema.
    </xsd:documentation>
  </xsd:annotation>
  
  <xsd:simpleType name="monsterNumberType">
   <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|([0-9]*-[0-9]*)|S|S \(mounts\)"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:complexType name="magicType">
    <xsd:attribute name="id"    type="xsd:string"/>
    <xsd:attribute name="level" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>
  
  <xsd:complexType name="ruleType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  
  <xsd:complexType name="specialType">
    <xsd:sequence>
      <xsd:element name="text" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="magic" type="magicType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="append" type="xsd:boolean" />
  </xsd:complexType>
  
  <xsd:complexType name="monsterType">
    <xsd:sequence minOccurs="0" maxOccurs="1">
      <xsd:element name="special" type="specialType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="number" type="monsterNumberType" />
  </xsd:complexType>
  
  <xsd:complexType name="eventType">
    <xsd:attribute name="id" type="xsd:string" />
  </xsd:complexType>
  
  <xsd:complexType name="groupType">
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="monster" type="monsterType" />
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="tableType">
    <xsd:sequence maxOccurs="unbounded" minOccurs="1">
      <xsd:choice>
        <xsd:element name="monster" type="monsterType" />
        <xsd:element name="event" type="eventType" />
        <xsd:element name="group" type="groupType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" />
  </xsd:complexType>

  <xsd:element name="tables">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="table" type="tableType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
</xsd:schema>

=== psiegel/eventdeck/data/xml/tables/originaldeck-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Original Event Deck">
    <monster id="od-giant-bat" number="2-12" />
    <monster id="od-giant-rat" number="2-12" />
    <monster id="od-giant-spider" number="2-12" />
    <monster id="od-snotling" number="2-12" />
    <monster id="od-goblin-archer" number="6" />
    <monster id="od-goblin-spearman" number="6" />
    <group>
      <monster id="od-goblin-archer" number="1-6" />
      <monster id="od-goblin-spearman" number="1-6" />
    </group>
    <monster id="od-skaven" number="2-12" />
    <monster id="od-orc" number="6" />
    <group>
      <monster id="od-orc" number="1-6" />
      <monster id="od-orc-archer" number="1-6" />
    </group>
    <monster id="od-minotaur-solo" number="1" />
    <monster id="od-minotaur" number="1-3" />
    <event id="od-old-bones" />
    <event id="od-scorpions" />
    <event id="od-encounter" />
    <event id="od-trap" />
    <event id="od-dead-body" />
    <event id="od-portcullis" />
    <event id="od-cave-in" />
  </table>
</tables>

=== psiegel/eventdeck/data/xml/tables/rpbook-dungeon-event-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Roleplay Book Dungeon Events Table">
    <event id="rpb-cave-in" />
    <event id="rpb-dead-body" />
    <event id="rpb-encounter-dying-dwarf" />
    <event id="rpb-encounter-warrior" />
    <event id="rpb-encounter-sneaky-git" />
    <event id="rpb-encounter-ghost" />
    <event id="rpb-encounter-prisoners" />
    <event id="rpb-encounter-stranger" />
    <event id="rpb-encounter-gold-digger" />
    <event id="rpb-encounter-nurgle's-rot" />
    <event id="rpb-scorpion-swarm" />
    <event id="rpb-snakes" />
    <event id="rpb-trap" />
    <event id="rpb-trap-spiked-pit" />
    <event id="trap-poison-dart" />
    <event id="rpb-trap-stone-block" />
    <event id="rpb-trap-paralysis-spell" />
    <event id="rpb-trap-gaseous-explosion" />
    <event id="rpb-trap-lightning-bolt" />
    <event id="rpb-old-bones" />
    <event id="rpb-locked-door" />
    <event id="rpb-portcullis" />
    <event id="rpb-lost" />
    <event id="rpb-the-flames-of-khazla" />
    <event id="rpb-footprints" />
    <event id="rpb-slaves" />
    <event id="rpb-dying-orc" />
    <event id="rpb-change-of-plan" />
    <event id="rpb-secret-door" />
    <event id="rpb-lost-gold" />
    <event id="rpb-daylight?" />
    <event id="rpb-missed-footing" />
    <event id="rpb-orc-runes" />
    <event id="rpb-lantern-goes-out" />
    <event id="rpb-imperial-knight" />
    <event id="rpb-curse-of-hashakk" />
  </table>
</tables>
