=== psiegel/eventdeck/debug/whq-monster-schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Warhammer Quest Monster and Event table schema.
    </xsd:documentation>
  </xsd:annotation>
  
  <xsd:simpleType name="intOrDashOrSpecial">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|-|S"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="ballisticSkillType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|Auto|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="attackType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|([0-9]*D6)|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="damageType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9]*D6)|([0-9]*D6\/[0-9]*D6\([0-9]\+\))|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:complexType name="ruleType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="magicType">
    <xsd:attribute name="id"    type="xsd:string"/>
    <xsd:attribute name="level" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>
  
  <xsd:complexType name="specialType">
    <xsd:sequence>
      <xsd:element name="text" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="magic" type="magicType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="monsterType">
    <xsd:all>
      <xsd:element name="wounds"         type="intOrDashOrSpecial" />
      <xsd:element name="move"           type="intOrDashOrSpecial" />
      <xsd:element name="weaponskill"    type="intOrDashOrSpecial" />
      <xsd:element name="ballisticskill" type="ballisticSkillType" />
      <xsd:element name="strength"       type="intOrDashOrSpecial" />
      <xsd:element name="toughness"      type="intOrDashOrSpecial" />
      <xsd:element name="initiative"     type="intOrDashOrSpecial" />
      <xsd:element name="attacks"        type="attackType" />
      <xsd:element name="gold"           type="intOrDashOrSpecial" />
      <xsd:element name="armor"          type="intOrDashOrSpecial" />
      <xsd:element name="damage"         type="damageType" />
      <xsd:element name="special"        type="specialType" />
    </xsd:all>
    <xsd:attribute name="id"     type="xsd:string" />
    <xsd:attribute name="name"   type="xsd:string" />
    <xsd:attribute name="plural" type="xsd:string" />
  </xsd:complexType>


  <xsd:element name="monsters">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="monster" type="monsterType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== psiegel/eventdeck/data/xml/monsters/rpbook-dark-elves.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>
  <monster id="rpb-dark-elf-warrior" name="Dark Elf Warrior" 
           plural="Dark Elf Warriors">
    <wounds>6</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <initiative>6</initiative>
    <attacks>1</attacks>
    <gold>100</gold>
    <armor>1</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with">Armed with Crossbows (Str 4)</rule>
      <rule id="rpb-dodge">Dodge 6+</rule>
      <rule id="rpb-hate">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-champion" name="Dark Elf Champion" 
           plural="Dark Elf Champions">
    <wounds>14</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>5</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>2</attacks>
    <gold>480</gold>
    <armor>2</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-dodge">Dodge 6+</rule>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-hero" name="Dark Elf Hero" plural="Dark Elf Heroes">
    <wounds>25</wounds>
    <move>5</move>
    <weaponskill>6</weaponskill>
    <ballisticskill>1</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>8</initiative>
    <attacks>3</attacks>
    <gold>1040</gold>
    <armor>4</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-dodge">Dodge 4+</rule>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 5+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-lord" name="Dark Elf Lord" plural="Dark Elf Lords">
    <wounds>34</wounds>
    <move>5</move>
    <weaponskill>7</weaponskill>
    <ballisticskill>Auto</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>9</initiative>
    <attacks>4</attacks>
    <gold>1600</gold>
    <armor>4</armor>
    <damage>3D6</damage>
    <special>
      <rule id="rpb-dodge">Dodge 4+</rule>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 5+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">2 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-assassin" name="Dark Elf Assassin" 
           plural="Dark Elf Assassins">
    <wounds>12</wounds>
    <move>5</move>
    <weaponskill>9</weaponskill>
    <ballisticskill>Auto</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>10</initiative>
    <attacks>2</attacks>
    <gold>410</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-ambush-magic">Ambush, Magic 5+</rule>
      <rule id="rpb-assassinate">Assassinate 6+</rule>
      <rule id="rpb-dodge">Dodge 5+</rule>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-weeping-blade">Weeping Blades</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-beastmaster" name="Dark Elf Beastmaster" 
           plural="Dark Elf Beastmasters">
    <wounds>15</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>2</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>2</attacks>
    <gold>150</gold>
    <armor>2</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with">Armed with Crossbow (Str 5)</rule>
      <rule id="rpb-beast-handler">Beast Handler</rule>
      <rule id="rpb-hate">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-sorcerer" name="Dark Elf Sorcerer" 
           plural="Dark Elf Sorcerers">
    <wounds>12</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <initiative>7</initiative>
    <attacks>1</attacks>
    <gold>590</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 6+</rule>
      <rule id="rpb-magic-item">Magic Item</rule>
      <magic id="rpb-dark-elf" level="1" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-sorcerer-champion" name="Dark Elf Sorcerer Champion"    
           plural="Dark Elf Sorcerer Champions">
    <wounds>20</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>7</initiative>
    <attacks>1</attacks>
    <gold>1210</gold>
    <armor>1</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 5+</rule>
      <rule id="rpb-magic-item">Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-dark-elf" level="2" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-master-sorcerer" name="Dark Elf Master Sorcerer"
           plural="Dark Elf Master Sorcerer">
    <wounds>30</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>8</initiative>
    <attacks>2</attacks>
    <gold>2190</gold>
    <armor>2</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-magic-dispel">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 4+</rule>
      <rule id="rpb-magic-item">2 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-dark-elf" level="3" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-sorcerer-lord" name="Dark Elf Sorcerer Lord"
           plural="Dark Elf Socrerer Lords">
    <wounds>41</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>9</initiative>
    <attacks>3</attacks>
    <gold>3280</gold>
    <armor>3</armor>
    <damage>3D6</damage>
    <special>
      <rule id="rpb-ambush-magic">Ambush, Magic A</rule>
      <rule id="rpb-hate">Hate Elves</rule>
      <rule id="rpb-magic-dispel">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 3+</rule>
      <rule id="rpb-magic-item">3 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-dark-elf" level="4" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-naggaroth-black-guard"
           name="Dark Elf Naggaroth Black Guard" 
           plural="Dark Elf Naggaroth Black Guards">
    <wounds>6</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>1</attacks>
    <gold>150</gold>
    <armor>2</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with">Armed with Halberds</rule>
      <rule id="rpb-fight-in-ranks">Fight in Ranks</rule>
      <rule id="rpb-hate">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-witch-elf" name="Witch Elf" plural="Witch Elves">
    <wounds>11</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <initiative>6</initiative>
    <attacks>1</attacks>
    <gold>140</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-frenzy">Frenzy 4+</rule>
      <rule id="rpb-hate">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-witch-elf-champion" name="Witch Elf Champion" 
           plural="Witch Elf Champions">
    <wounds>13</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>2</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>2</attacks>
    <gold>600</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-frenzy">Frenzy 3+</rule>
      <rule id="rpb-hate">Hate Elves</rule>
    </special>
  </monster>
</monsters>

=== psiegel/eventdeck/data/xml/monsters/originaldeck-monsters.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>

  <monster id="od-giant-bat" name="Giant Bat" plural="Giant Bats">
    <move>8</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>2</strength>
    <toughness>2</toughness>
    <wounds>1</wounds>
    <initiative>-</initiative>
    <attacks>1</attacks>
    <gold>15</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>Giant Bats make an immediate attack as soon as they are placed on the board and then attack as normal in the Monsters' Phase.
After the first Turn, the combat sequence returns to normal.
Bats are never pinned and will change target each turn if possible.</text></special>
  </monster>
  <monster id="od-giant-rat" name="Giant Rat" plural="Giant Rats">
    <move>6</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>1</wounds>
    <initiative>4</initiative>
    <attacks>1</attacks>
    <gold>25</gold>
    <armor>-</armor>
    <damage>5D6</damage>
    <special><text>When a Giant Rat hits your Warrior, roll 2 dice to see how many Wounds it causes, and add its Strength (2) to the score.
Once a Giant Rat has attacked your Warrior, roll 1D6.  On a 3+ the Giant Rat's sucidial, frenzied attack has opened it up to your Warrior's attacks and he kills it automatically.</text></special>
  </monster>
  <monster id="od-giant-spider" name="Giant Spider" plural="Giant Spiders">
    <move>6</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>S</strength>
    <toughness>2</toughness>
    <wounds>1</wounds>
    <initiative>-</initiative>
    <attacks>1</attacks>
    <gold>15</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>If a Spider attacks a Warrior who is already webbed, the Spider automatically bites him inflicting 1D3 Wounds with no modifiers for Toughness or armour.
If the Warrior wasn't already webbed, make a roll to hit.  If the Spider hits, the Warrior is now webbed and may do nothing until he gets free.  Put a Webbed counter next to him.
At the start of each turn roll 1D6 for each webbed Warrior and add his Strength.  If the total is 7 or more, he frees himself and may act normally.</text></special>
  </monster>
  <monster id="od-snotling" name="Snotling" plural="Snotlings">
    <move>4</move>
    <weaponskill>1</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>1</strength>
    <toughness>1</toughness>
    <wounds>1</wounds>
    <initiative>1</initiative>
    <attacks>1</attacks>
    <gold>10</gold>
    <armor>-</armor>
    <damage>S</damage>
    <special><text>Snotlings make an immediate attack as soon as they are placed on the board and then attack as normal in the Monsters' Phase.
Draw a Warrior counter and place as many Snotlings as you can around that Warrior.  Repeat until all the Snotlings have been placed.
For each Snotling above one in combat with a Warrior, add +1 to their hit roll and increase their Strength by +1: e.g., 4 Snotlings make a single Strength 4 attack with +3 on the to hit roll.
Snotlings do not switch attacks unless their target dies, and will fight until killed.</text></special>
  </monster>
  <monster id="od-goblin-archer" name="Goblin Archer" plural="Goblin Archers">
    <move>4</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>5</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>2</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>20</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>When shooting with their bows, Night Goblin archers need to roll a 5 or more to hit.  A Goblin's bow has Stength 1, and causes 1D6+1 Wounds.
Before fighting the Night Goblin archers, take another Event card.</text></special>
  </monster>
  <monster id="od-goblin-spearman" 
           name="Goblin Spearman" plural="Goblin Spearmen">
    <move>4</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>5</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>2</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>20</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>When shooting with their bows, Night Goblin archers need to roll a 5 or more to hit.  A Goblin's bow has Stength 1, and causes 1D6+1 Wounds.
Goblins armed with spears may attack from 2 squares away, even past intervening Monsters and Warriors.</text></special>
  </monster>
  <monster id="od-skaven" name="Skaven" plural="Skaven">
    <move>5</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>3</wounds>
    <initiative>4</initiative>
    <attacks>1</attacks>
    <gold>40</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text></text></special>
  </monster>
  <monster id="od-orc" name="Orc" plural="Orcs">
    <move>4</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <wounds>3</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>55</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text></text></special>
  </monster>
  <monster id="od-orc-archer" name="Orc Archer" plural="Orc Archers">
    <move>4</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <wounds>3</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>55</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>When shooting with their bows, Orc archers need to roll a 4 or more to hit.  An Orc's bow has Strength 3, and causes 1D6+3 Wounds.</text></special>
  </monster>
  <monster id="od-minotaur-solo" name="Minotaur" plural="Minotaurs">
    <move>6</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <wounds>15</wounds>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>440</gold>
    <armor>-</armor>
    <damage>2D6</damage>
    <special><text>When a Minotaur hits a Warrior, roll 2 dice to see how many Wounds it causes, adding its Strength of 4 to the total.
Before fighting the Minotaur, take another Event card.  If this is an Event, resolve it before fighting the Minotaur.  If it reveals more Monsters, fight them all at once.</text></special>
  </monster>
  <monster id="od-minotaur" name="Minotaur" plural="Minotaurs">
    <move>6</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <wounds>15</wounds>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>440</gold>
    <armor>-</armor>
    <damage>2D6</damage>
    <special><text>When a Minotaur hits a Warrior, roll 2 dice to see how many Wounds it causes, adding its Strength of 4 to the total.</text></special>
  </monster>
</monsters>

=== psiegel/eventdeck/debug/debug-monster.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>
  <monster id="debug-ogre" name="DEBUG Ogre" plural="DEBUG Ogres">
    <wounds>13</wounds>
    <move>6</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>5</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>400</gold>
    <armor>0</armor>
    <damage>1D6/2D6(5+)</damage>
    <special>
      <text>This is the text.  It is some very long text.  It goes on and on without end.  Dear Lord, when will this text ever end.  Ah, this looks like the end.
Oh no, that was just a line break!  It still goes on.  Make it stop!!  Make it stop!!!</text>
      <rule id="rpb-ambush-magic">Ambush, Magic A</rule>
      <rule id="rpb-armed-with">Armed with Spears (Str 3)</rule>
      <rule id="rpb-vampire">Vampire</rule>
      <magic id="rpb-necromantic" level="1" />
    </special>
  </monster>
</monsters>

=== psiegel/eventdeck/data/xml/monsters/rpbook-chaos-dwarfs.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>
  <monster id="rpb-chaos-dwarf" name="Chaos Dwarf" plural="Chaos Dwarfs">
    <wounds>8</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>140</gold>
    <armor>2</armor>
    <damage>1D6/2D6(6+)</damage>
    <special>
      <rule id="rpb-magic-resistance">Magic Resistance 6+</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-blunderbuss" 
           name="Chaos Dwarf with Blunderbuss" 
           plural="Chaos Dwarfs with Blunderbuss">
    <wounds>8</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>140</gold>
    <armor>1</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with">Armed with Blunderbuss</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 6+</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-champion" name="Chaos Dwarf Champion" 
           plural="Chaos Dwarf Champions">
    <wounds>16</wounds>
    <move>3</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>3</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>480</gold>
    <armor>2</armor>
    <damage>2D6/3D6(5+)</damage>
    <special>
      <rule id="rpb-magic-resistance">Magic Resistance 6+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-lord" name="Chaos Dwarf Lord" 
           plural="Chaos Dwarf Lords">
    <wounds>33</wounds>
    <move>3</move>
    <weaponskill>7</weaponskill>
    <ballisticskill>1</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <initiative>5</initiative>
    <attacks>4</attacks>
    <gold>1600</gold>
    <armor>3</armor>
    <damage>3D6</damage>
    <special>
      <rule id="rpb-magic-resistance">Magic Resistance 5+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">2 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-sorcerer" name="Chaos Dwarf Sorcerer" 
           plural="Chaos Dwarf Sorcerers">
    <wounds>8</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>3</strength>
    <toughness>6</toughness>
    <initiative>3</initiative>
    <attacks>1</attacks>
    <gold>590</gold>
    <armor>2</armor>
    <damage>1D6/2D6(6+)</damage>
    <special>
      <rule id="rpb-magic-dispel">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 4+</rule>
      <rule id="rpb-protection-ring">Protection Ring (+1 T)</rule>
      <magic id="rpb-chaos-dwarf" level="1" />
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-master-sorcerer" 
           name="Chaos Dwarf Master Sorcerer" 
           plural="Chaos Dwarf Master Sorcerers">
    <wounds>26</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <initiative>4</initiative>
    <attacks>2</attacks>
    <gold>2190</gold>
    <armor>3</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-magic-dispel">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 4+</rule>
      <rule id="rpb-magic-armour">Magic Armour; Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-chaos-dwarf" level="3" />
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-sorcerer-lord" name="Chaos Dwarf Sorcerer Lord" 
           plural="Chaos Dwarf Sorcerer Lord">
    <wounds>40</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <initiative>5</initiative>
    <attacks>3</attacks>
    <gold>3280</gold>
    <armor>3</armor>
    <damage>3D6/4D6(5+)</damage>
    <special>
      <rule id="rpb-magic-dispel">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance">Magic Resistance 3+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">3 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-chaos-dwarf" level="4" />
    </special>
  </monster>
</monsters>
